### ISSUE TITLE
Deploying a Sample Application does not work

### ISSUE THREAD

**Issue by rokkanen** [redhat-developer/s2i-dotnetcore-ex#18] opened 2017-01-23 17:28 UTC
I tried worklow describe here
https://developers.redhat.com/blog/2016/06/16/simplifying-asp-net-applications-on-openshift-with-the-asp-net-core-s2i-builder/

git clone https://github.com/openshift-s2i/s2i-aspnet-example
OK
oc new-project ose-dotnet
OK
oc new-app --template=aspnet-s2i –p GIT_URI=https://github.com/openshift-s2i/s2i-aspnet-example
I've obtained this:

--> Deploying template aspnet-s2i

     aspnet-s2i
     ---------
     Application template for asp .NET applications

     * With parameters:
        * Memory Limit=512Mi
        * Application Name=aspnet-app
        * Git URI=https://github.com/openshift-s2i/s2i-aspnet-example
        * Git Branch=master
        * Git Context Directory=app
        * Application hostname=
        * Upstream S2I Image=registry.access.redhat.com/dotnet/dotnetcore-10-rhel7
        * Upstream S2I Image Tag=latest
        * GitHub Webhook Secret=W2HAwCLF # generated
        * Generic Webhook Secret=Cl3TQXov # generated
--> Creating resources with label app=aspnet-s2i ...
    imagestream "aspnet-app" created
    imagestream "s2i-aspnet" created
    service "aspnet-app" created
    buildconfig "aspnet-app" created
    error: DeploymentConfig "aspnet-app" is invalid: spec.template.metadata.labels: Invalid value: {"app":"aspnet-s2i","deploymentconfig":"aspnet-app"}: `selector` does not match template `labels`
    route "aspnet-app" created
--> Failed

in Openshift portal/monitoring/Event table:

Time	        Name	        Kind	                Severity	Reason	Message
11:34:52 PM	aspnet-app	Build Config	Warning	Build config instantiate failed 	error instantiating Build from BuildConfig ose-dotnet/aspnet-app: Error resolving ImageStreamTag s2i-aspnet:latest in namespace ose-dotnet: imagestreamtags "s2i-aspnet:latest" not found

My configuration:

Windows 10 Aniversary - Lenovo X1 16Go Ram
Docker for Windows Version 1.13.0 (9795) (Default configuration)
openshift launched with following command:
c:\>oc cluster up --version=v1.4.0 --routing-suffix=10.0.75.2.nip.io

Thank's for your help.

**Comment by jerboaa** [comment] 2017-01-23 17:47
Yes, the template seems broken. I didn't have time to fix it yet. It's in progress. The manual steps should work though:

    oc new-app registry.access.redhat.com/dotnet/dotnetcore-10-rhel7~https://github.com/redhat-developer/s2i-dotnetcore-ex --name=aspnet-app --context-dir=app
    oc expose service aspnet-app

Let me know how that goes.

**Comment by rokkanen** [comment] 2017-01-23 18:06
awesome !!!
Thank's you very much Severin for your reactivity, it works !

**Comment by jerboaa** [comment] 2017-01-23 18:26
Closing as duplicate of issue #13. The template will get fixed using that issue.

**Closed by jerboaa** 2017-01-23 18:26 UTC
Labels: bug, duplicate

**Comment by jerboaa** [comment] 2017-01-27 09:27
I was wrong, #13 is a permission issue. Not a duplicate of this. Anyway, this issue should be fixed with abf637a09a8eb15ece2728a8e1f886152f9ee7e1
