### ISSUE TITLE
Creating template does not work

### ISSUE THREAD

**Issue by charlesrichard** [redhat-developer/s2i-dotnetcore-ex#13] opened 2016-09-03 02:23 UTC
Executing 

> oc create -f templates/aspnet-s2i-template.json -n openshift

 or 

> oc create templates/aspnet-s2i-template.json -n openshift

does not work. This is a relative path.

**Comment by alberttwong** [comment] 2016-09-03 04:55
what is the commands did you run?   There is also an assumption that you would have git cloned this project into your location machine before running the oc create command.

**Comment by alberttwong** [comment] 2016-09-08 22:23
@charlesrichard Do you have a status on this issue?

**Comment by jerboaa** [comment] 2017-01-27 09:25
This actually isn't a duplicate of #18, but seems to be a permission issue. When I try this I get:

    $ oc create -f templates/aspnet-s2i-template.json -n openshift
    Error from server: error when creating "templates/aspnet-s2i-template.json": User "developer" cannot create templates in project "openshift"

And indeed I (developer) don't have write/view access to project openshift:

    $ oc get projects | grep openshift
    <nothing>

This works when logged in as `system:admin` for example:

    $ oc whoami
    system:admin
    $ oc create -f aspnet-s2i-template.json -n openshift
    template "aspnet-s2i" created
    $ oc get projects | grep openshift
    openshift                           Active
    openshift-infra                     Active

There is nothing the sample app can do other than updating the documentation, which I'll do as a follow up. Closing this issue.

**Closed by jerboaa** 2017-01-27 09:25 UTC

**Comment by jerboaa** [comment] 2017-01-27 11:24
> There is nothing the sample app can do other than updating the documentation, which I'll do as a follow up. 

Actually from the README:

     "Using a user with permissions to modify resources in the openshift project ..."

So it is documented.
